kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zones: eu-west1-d
---
# kubectl apply -f autosuggest-infra.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autosuggest-db-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: autosuggest-catalog-db-disk-dev
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autosuggest-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# kubectl apply -f autosuggest-infra.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autosuggest-cache-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: autosuggest-cache-disk-dev
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autosuggest-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

