---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: autosuggest-app-deployment
  labels:
    app: autosuggest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autosuggest-app
  template:
    metadata:
      labels:
        app: autosuggest-app
        tier: frontend
    spec:
      containers:
      - name: autosuggest-app
        image: "eu.gcr.io/autosuggest-194816/autosuggest-app:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: autosuggest-app-service
spec:
  selector:
    app: autosuggest-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30061
  type: LoadBalancer
---  
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: autosuggest-catalog-deployment
  labels:
    app: autosuggest-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autosuggest-catalog
  template:
    metadata:
      labels:
        app: autosuggest-catalog
        tier: backend
    spec:
      containers:
      - name: autosuggest-catalog
        image: "eu.gcr.io/autosuggest-194816/autosuggest-catalog:latest"
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: catalog-db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalog-db-secret
                key: password
          - name: DB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalog-db-secret
                key: admin-password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: autosuggest-catalog-service
spec:
  selector:
    app: autosuggest-catalog
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30071
  type: LoadBalancer
---  
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: autosuggest-cache-deployment
  labels:
    app: autosuggest-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autosuggest-cache
  template:
    metadata:
      labels:
        app: autosuggest-cache
        tier: backend
    spec:
      containers:
      - name: autosuggest-cache
        image: "eu.gcr.io/autosuggest-194816/autosuggest-cache:latest"
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: catalog-cache-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalog-cache-secret
                key: password
          - name: DB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalog-cache-secret
                key: admin-password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: autosuggest-cache-service
spec:
  selector:
    app: autosuggest-cache
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30071
  type: LoadBalancer